name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_BUILD: cp36-*
          CIBW_ARCHS_WINDOWS: x86

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
